---
- name: generating in-memory inventory
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers
      tags:
        - everything

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group:
          - "{{ item.metadata.group }}"
          - "{{ item.metadata.deployment_name }}"
      loop: "{{ r_os_servers.openstack_servers }}"
      tags: 
        - everything

- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers
    - everything
  roles:
    - postgres

- name: Deploy, configure, and populate flask repo and virtualenv
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask
    - everything
  roles:
    - app

- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false
  become: true

  tags:
    - load_balancers
    - everything
  roles:
    - load_balancers

